[project]
name = "dbt-ansh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fizza Alwani", email = "fizzaalwani@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-databricks>=1.10.9",
]

[project.scripts]
dbt-ansh = "dbt_ansh:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
