
name: 'dbt_practice_ansh'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_practice_ansh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_practice_ansh:
    # Config indicated by + and applies to all files under models/example/
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    golden:
      +materialized: table
      +schema: golden
    
